services:
  db:
    image: postgres:18
    container_name: healthion-api-postgres
    environment:
      POSTGRES_DB: healthion
      POSTGRES_USER: healthion
      POSTGRES_PASSWORD: healthion
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: scripts/start/app.sh
    container_name: healthion-api-app
    env_file:
      - ./envs/.env
    environment:
      - DB_HOST=db
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/root_project
      - /root_project/.venv
      - type: bind
        source: ./envs/.env
        target: /root_project/envs/.env
        bind:
          create_host_path: false
    restart: on-failure

volumes:
  postgres_data:
