"""apple-mcp

Revision ID: 161c6716451a
Revises: 888e359b8ac9

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '161c6716451a'
down_revision: Union[str, None] = '888e359b8ac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('sourceVersion', sa.String(length=100), nullable=False),
    sa.Column('sourceName', sa.String(length=100), nullable=False),
    sa.Column('deviceId', sa.String(length=100), nullable=False),
    sa.Column('startDate', sa.DateTime(timezone=True), nullable=False),
    sa.Column('endDate', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creationDate', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Numeric(precision=15, scale=5), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workoutstatistic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('startDate', sa.DateTime(timezone=True), nullable=False),
    sa.Column('endDate', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creationDate', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sum', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('average', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('maximum', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('minimum', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xmlworkout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('durationUnit', sa.String(length=10), nullable=False),
    sa.Column('sourceName', sa.String(length=100), nullable=False),
    sa.Column('startDate', sa.DateTime(timezone=True), nullable=False),
    sa.Column('endDate', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creationDate', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('xmlworkout')
    op.drop_table('workoutstatistic')
    op.drop_table('record')
    # ### end Alembic commands ###
