"""foreign key

Revision ID: 6bb12525e21b
Revises: 791d2bb9ba20

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bb12525e21b'
down_revision: Union[str, None] = '791d2bb9ba20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('activeenergy_workout_id_fkey'), 'activeenergy', type_='foreignkey')
    op.create_foreign_key(None, 'activeenergy', 'newworkout', ['workout_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('heartratedata_workout_id_fkey'), 'heartratedata', type_='foreignkey')
    op.create_foreign_key(None, 'heartratedata', 'newworkout', ['workout_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('heartraterecovery_workout_id_fkey'), 'heartraterecovery', type_='foreignkey')
    op.create_foreign_key(None, 'heartraterecovery', 'newworkout', ['workout_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'heartraterecovery', type_='foreignkey')
    op.create_foreign_key(op.f('heartraterecovery_workout_id_fkey'), 'heartraterecovery', 'workout', ['workout_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'heartratedata', type_='foreignkey')
    op.create_foreign_key(op.f('heartratedata_workout_id_fkey'), 'heartratedata', 'workout', ['workout_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'activeenergy', type_='foreignkey')
    op.create_foreign_key(op.f('activeenergy_workout_id_fkey'), 'activeenergy', 'workout', ['workout_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
