"""init

Revision ID: 70f784d3b912
Revises: 

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70f784d3b912'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration', sa.Numeric(precision=15, scale=5), nullable=True),
    sa.Column('active_energy_burned_qty', sa.Numeric(precision=15, scale=5), nullable=True),
    sa.Column('active_energy_burned_units', sa.String(length=50), nullable=True),
    sa.Column('distance_qty', sa.Numeric(precision=15, scale=5), nullable=True),
    sa.Column('distance_units', sa.String(length=50), nullable=True),
    sa.Column('intensity_qty', sa.Numeric(precision=15, scale=5), nullable=True),
    sa.Column('intensity_units', sa.String(length=50), nullable=True),
    sa.Column('humidity_qty', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('humidity_units', sa.String(length=10), nullable=True),
    sa.Column('temperature_qty', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('temperature_units', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activeenergy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('units', sa.String(length=50), nullable=True),
    sa.Column('qty', sa.Numeric(precision=15, scale=5), nullable=True),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heartratedata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('units', sa.String(length=50), nullable=True),
    sa.Column('avg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('min', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('max', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heartraterecovery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('units', sa.String(length=50), nullable=True),
    sa.Column('avg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('min', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('max', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('heartraterecovery')
    op.drop_table('heartratedata')
    op.drop_table('activeenergy')
    op.drop_table('workout')
    # ### end Alembic commands ###
