"""add user_id

Revision ID: 790a68ddc1d6
Revises: 161c6716451a

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '790a68ddc1d6'
down_revision: Union[str, None] = '161c6716451a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'record', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('workoutstatistic', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'workoutstatistic', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('xmlworkout', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'xmlworkout', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'xmlworkout', type_='foreignkey')
    op.drop_column('xmlworkout', 'user_id')
    op.drop_constraint(None, 'workoutstatistic', type_='foreignkey')
    op.drop_column('workoutstatistic', 'user_id')
    op.drop_constraint(None, 'record', type_='foreignkey')
    op.drop_column('record', 'user_id')
    # ### end Alembic commands ###
