"""workout statistic support

Revision ID: 791d2bb9ba20
Revises: 21b31fe8c473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '791d2bb9ba20'
down_revision: Union[str, None] = '21b31fe8c473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workoutstatistic', sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False))
    op.drop_column('workoutstatistic', 'average')
    op.drop_column('workoutstatistic', 'endDate')
    op.drop_column('workoutstatistic', 'startDate')
    op.drop_column('workoutstatistic', 'minimum')
    op.drop_column('workoutstatistic', 'maximum')
    op.drop_column('workoutstatistic', 'sum')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workoutstatistic', sa.Column('sum', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('workoutstatistic', sa.Column('maximum', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('workoutstatistic', sa.Column('minimum', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('workoutstatistic', sa.Column('startDate', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('workoutstatistic', sa.Column('endDate', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('workoutstatistic', sa.Column('average', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_column('workoutstatistic', 'value')
    # ### end Alembic commands ###
